services:
  broker:
      build: ./broker
      container_name: broker-service
      ports:
        - "9000:9000"
      expose:
        - 9000
      depends_on:
        - auldfellas
        - dodgygeezers
        - girlsallowed
  auldfellas:
    build: ./auldfellas
    container_name: afq-service
  dodgygeezers:
    build: ./dodgygeezers
    container_name: dgq-service
  girlsallowed:
    build: ./girlsallowed
    container_name: gaq-service
