version: "2.31"

services:
  broker:
      build:
          context: ./broker
          dockerfile: Dockerfile
      container_name: broker-service
      ports:
        - "9000:9000"
      expose:
        - 9000
  auldfellas:
    build:
      context: ./auldfellas
      dockerfile: Dockerfile
    container_name: auldfellas-service
  dodgygeezers:
    build:
      context: ./dodgygeezers
      dockerfile: Dockerfile
    container_name: dodgygeezers-service
  girlsallowed:
    build:
      context: ./girlsallowed
      dockerfile: Dockerfile
    container_name: girlsallowed-service